version: "3"

services:

  nginx:
    build:
      context: web      
    container_name: nginx-fullcycle  
    entrypoint: dockerize -wait tcp://api:8080 -timeout 10s /docker-entrypoint.sh nginx -g "daemon off;"
    ports: 
      - 8080:8080
    networks: 
      - backend
      - frontend
    restart: always
    depends_on: 
      - api

  api:
    build:
      context: api   
    container_name: node-fullcycle
    entrypoint: dockerize -wait tcp://db:3306 -timeout 10s node index.js
    networks:
      - backend
    restart: always
    depends_on: 
      - db

  db:
    build:
      context: db
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-fullcycle
    volumes:
        # - ./dbdata:/var/lib/mysql
        - ./db:/docker-entrypoint-initdb.d
    restart: always
    tty: true
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=docker
    networks:
      - backend
    

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge